//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulkCreateRechargeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class FailureLog
    {
        public int id { get; set; }
        public string Client_Id { get; set; }
        public string Client_Pass { get; set; }
        public string Guid { get; set; }
        public string Vr_guid { get; set; }
        public Nullable<System.DateTime> recharge_date { get; set; }
    }
}
