//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulkCreateRechargeApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class api_logs
    {
        public long log_id { get; set; }
        public string log_date { get; set; }
        public string visitor_ip { get; set; }
        public string client_id { get; set; }
        public string function { get; set; }
        public string feature { get; set; }
        public string action_status { get; set; }
        public string details { get; set; }
    }
}
