//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulkInitRechargeSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class RechargeInfoTbl
    {
        public int id { get; set; }
        public string client_id { get; set; }
        public string client_pass { get; set; }
        public string guid { get; set; }
        public string vr_guid { get; set; }
        public int operator_id { get; set; }
        public string recepient_msisdn { get; set; }
        public int amount { get; set; }
        public string connection_type { get; set; }
        public string create_recharge_Status { get; set; }
        public string init_recharge_status { get; set; }
        public Nullable<System.DateTime> RequestDateTime { get; set; }
        public Nullable<System.DateTime> SentDateTime { get; set; }
        public Nullable<System.DateTime> ResponseDateTime { get; set; }
        public Nullable<int> Create_Try { get; set; }
        public Nullable<int> Init_try { get; set; }
        public string Create_Status_Code { get; set; }
        public string Init_Status_Code { get; set; }
        public Nullable<System.DateTime> in_time { get; set; }
    }
}
